NAME = so_long
BONUS = so_long_bonus

SRC_DIR = src
BONUS_DIR = bonus
INCLUDE_DIR = includes
OBJ_DIR = obj
OBJ_BONUS_DIR = obj_bonus
LIBFT_DIR = ./libs/libft
MLX_DIR = ./libs/MLX42

HEADER = $(INCLUDE_DIR)/so_long.h
BONUS_HEADER = $(INCLUDE_DIR)/so_long_bonus.h


# Fuentes normales
SRC_FILES = main.c

# Fuentes bonus
BONUS_FILES = 

# Rutas completas
SRCS = $(addprefix $(SRC_DIR)/, $(SRC_FILES))
BSRCS = $(addprefix $(BONUS_DIR)/, $(BONUS_FILES))

# Objetos
OBJS = $(addprefix $(OBJ_DIR)/, $(SRC_FILES:.c=.o))
OBJS_BONUS = $(addprefix $(OBJ_BONUS_DIR)/, $(BONUS_FILES:.c=.o))

LIBFT = $(LIBFT_DIR)/libft.a
MLX = $(MLX_DIR)/build/libmlx42.a
MLX_FLAGS = -ldl -lglfw -pthread -lm

CC = cc -g
CFLAGS = -Wall -Werror -Wextra -I$(INCLUDE_DIR) -I$(MLX_DIR)/include
RM = rm -rf

# Colores
GREEN = \033[1;32m
BLUE = \033[1;34m
YELLOW = \033[1;33m
RED = \033[1;31m
RESET = \033[0m

all: $(NAME)

$(LIBFT):
	@echo "$(BLUE)-> Compilando Libft...$(RESET)"
	@make -C $(LIBFT_DIR)
	@make -C $(LIBFT_DIR) bonus

$(NAME): $(OBJS) $(LIBFT) $(HEADER) Makefile
	@echo "$(GREEN)✔ Compilando $(NAME)...$(RESET)"
	@$(CC) $(CFLAGS) $(OBJS) $(LIBFT) $(MLX) $(MLX_FLAGS) -o $(NAME)
	@echo "$(GREEN)   Compilación completada!$(RESET)"

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	@echo "$(YELLOW)Compilando $<...$(RESET)"
	@$(CC) $(CFLAGS) -c $< -o $@

$(OBJ_DIR):
	@mkdir -p $(OBJ_DIR)

bonus: $(BONUS)

$(BONUS): $(OBJS_BONUS) $(LIBFT) $(BONUS_HEADER) Makefile
	@echo "$(GREEN)✔ Compilando $(BONUS)...$(RESET)"
	@$(CC) $(CFLAGS) $(OBJS_BONUS) $(LIBFT) $(MLX) $(MLX_FLAGS) -o $(BONUS)
	@echo "$(GREEN)   Compilación BONUS completada!$(RESET)"

$(OBJ_BONUS_DIR)/%.o: $(BONUS_DIR)/%.c | $(OBJ_BONUS_DIR)
	@echo "$(YELLOW)Compilando BONUS $<...$(RESET)"
	@$(CC) $(CFLAGS) -c $< -o $@

$(OBJ_BONUS_DIR):
	@mkdir -p $(OBJ_BONUS_DIR)

clean:
	@echo "$(RED)  Limpiando objetos...$(RESET)"
	@make -C $(LIBFT_DIR) clean
	@$(RM) $(OBJ_DIR) $(OBJ_BONUS_DIR)

f fclean: clean
	@echo "$(RED)  Borrando ejecutables...$(RESET)"
	@make -C $(LIBFT_DIR) fclean
	@$(RM) $(NAME) $(BONUS)

re: fclean all

.PHONY: all clean f fclean re bonus